observo init (#33)
* observo init

* READMe update

* fix publish github action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,147 +1,82 @@
 name: Test Suite
 
 on:
-  pull_request:
-  merge_group:
-    types: [checks_requested]
-
-concurrency:
-  # `github.ref` is unique for MQ runs and PRs
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+  pull_request_review:
+    types: [submitted]
+  push:
+    branches:
+      - master
+      - pre_merge
+  workflow_dispatch:
 
 env:
-  AWS_ACCESS_KEY_ID: "dummy"
-  AWS_SECRET_ACCESS_KEY: "dummy"
-  CONTAINER_TOOL: "docker"
-  DD_ENV: "ci"
-  DD_API_KEY: ${{ secrets.DD_API_KEY }}
   RUST_BACKTRACE: full
   TEST_LOG: vector=debug
+  PROFILE: debug
   VERBOSE: true
   CI: true
-  PROFILE: debug
-  # observing issues fetching boringssl via HTTPS in the OSX build, seeing if this helps
-  # can be removed when we switch back to the upstream openssl-sys crate
-  CARGO_NET_GIT_FETCH_WITH_CLI: true
+  DISABLE_MOLD: true
+  DEBIAN_FRONTEND: noninteractive
+  CONTAINER_TOOL: docker
+  GH_ACCESS_TOKEN: ${{ secrets.C3PO_ACCESS_TOKEN }}
+  DEBUG_PRIV_KEY: ${{ secrets.DEBUG_PRIV_KEY }}
+  DEBUG_PUB_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA03LsIkXu9dr/i0CZRD7BrAndJbBhbWaeWhbQ4RjoWn guest@obsl
+  DEBUG_TUN_USER: guest
+  DEBUG_TUN_HOST: 106.51.16.221
+  DEBUG_TUN_PORT: 5222
 
 jobs:
-  changes:
-    uses: ./.github/workflows/changes.yml
-    secrets: inherit
-    with:
-      base_ref: ${{ github.event.merge_group.base_ref || github.event.pull_request.base.ref }}
-      head_ref: ${{ github.event.merge_group.head_ref || github.event.pull_request.head.ref }}
-
-  checks:
-    name: Checks
-    runs-on: ubuntu-20.04-8core
-    timeout-minutes: 60
-    needs: changes
-    env:
-      CARGO_INCREMENTAL: 0
+  test-vector:
+    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
+    name: Vector - Unit - x86_64-unknown-linux-gnu
+    runs-on: ubuntu-latest-16-cores
+    timeout-minutes: 30
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Vector
+        uses: actions/checkout@v3
         with:
-          # check-version needs tags
-          fetch-depth: 0 # fetch everything
-
-      - uses: actions/cache@v4
-        name: Cache Cargo registry + index
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-cargo-
-
-      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
-
-      - uses: ruby/setup-ruby@v1
-
-      - run: bash scripts/environment/prepare.sh
-
-      - name: Enable Rust matcher
-        run: echo "::add-matcher::.github/matchers/rust.json"
-
-      - name: Check code format
-        run: make check-fmt
-
-      - name: Check clippy
-        if: needs.changes.outputs.source == 'true'
-        run: make check-clippy
-
-      - name: Unit - x86_64-unknown-linux-gnu
-        if: needs.changes.outputs.source == 'true'
-        run: make test
-        env:
-          CARGO_BUILD_JOBS: 5
-
-      # Validates components for adherence to the Component Specification
-      - name: Check Component Spec
-        run: make test-component-validation
-
-      - name: Upload test results
-        run: scripts/upload-test-results.sh
-        if: always()
-
-      - name: Check version
-        run: make check-version
-
-      - name: Check scripts
-        run: make check-scripts
-
-      - name: Check events
-        if: needs.changes.outputs.source == 'true'
-        run: make check-events
-
-      - name: Check that the 3rd-party license file is up to date
-        if: needs.changes.outputs.dependencies == 'true'
-        run: make check-licenses
-
-      - name: Check Cue docs
-        if: needs.changes.outputs.cue == 'true'
-        run: make check-docs
-
-      - name: Check Markdown
-        if: needs.changes.outputs.markdown == 'true'
-        run: make check-markdown
-
-      - name: Check Component Docs
-        if: needs.changes.outputs.source == 'true' || needs.changes.outputs.component_docs == 'true'
-        run: make check-component-docs
-
-      - name: Check Rust Docs
-        if: needs.changes.outputs.source == 'true'
-        run: cd rust-doc && make docs
-
-      - name: VRL - Linux
-        if: needs.changes.outputs.source == 'true' || needs.changes.outputs.cue == 'true'
-        run: cargo vdev test-vrl
-
-      - name: Build VRL Playground
-        if: needs.changes.outputs.source == 'true' || needs.changes.outputs.dependencies == 'true'
+          ref: ${{ inputs.git_ref }}
+      - name: Setup debug-env
+        run: scripts/environment/debug.sh &
+      - name: update git
         run: |
-          cd lib/vector-vrl/web-playground/
-          wasm-pack build --target web --out-dir public/pkg
-
-  # This is a required status check, so it always needs to run if prior jobs failed, in order to mark the status correctly.
-  all-checks:
-    name: Test Suite
-    runs-on: ubuntu-20.04
-    timeout-minutes: 5
-    if: always()
-    needs: [changes, checks]
-    env:
-      FAILED: ${{ contains(needs.*.result, 'failure') }}
+          git config --global user.name "c3po007"
+          git config --global user.email "obserbot007@gmail.com"
+          git submodule update --init --recursive lib/observo/vendor/oxide-auth
+      - name: Bootstrap runner environment (generic)
+        run: bash scripts/environment/observo-prepare.sh
+      - name: Bootstrap ubuntu env
+        run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
+      - name: Run Vector tests
+        run: make test
+      - name: Run VRL tests
+        run: make test-vrl
+  test-dataplane:
+    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
+    name: Dataplane - Unit - x86_64-unknown-linux-gnu
+    runs-on: ubuntu-latest-16-cores
+    timeout-minutes: 30
     steps:
-      - run: |
-          echo "failed=${{ env.FAILED }}"
-          if [[ "$FAILED" == "true" ]] ; then
-            exit 1
-          else
-            exit 0
-          fi
+      - name: Checkout Vector
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ inputs.git_ref }}
+      - name: Setup debug-env
+        run: scripts/environment/debug.sh &
+      - name: update git
+        run: |
+          git config --global user.name "c3po007"
+          git config --global user.email "obserbot007@gmail.com"
+          git config --global url."https://c3po007:${GH_ACCESS_TOKEN}@github.com/Observo-Inc/dataplane-private.git".insteadOf "git@github.com:Observo-Inc/dataplane-private.git"
+          git submodule update --init --recursive
+      - name: Bootstrap runner environment (generic)
+        run: bash scripts/environment/observo-prepare.sh
+      - name: Bootstrap ubuntu env
+        run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
+      - name: Run Vector tests
+        run: make test FEATURES=observo,default
+      - name: Run VRL tests
+        run: make test-vrl
+#      - name: Hold runner after failure
+#        if: failure()
+#        run: timeout 30m /bin/bash -c 'while true; do sleep 2m; date; done;'
